---
- hosts: raspi
  vars_files:
    - vars/vault_wifi_key.yml
    - vars/main.yml
  roles:
    - {role: raspi_common, become: yes}
    - {role: geerlingguy.firewall, become: yes}
    - {role: raspi_network}
    - {role: create_users, become: yes}
    - {role: docker, become: yes}
    - {role: dev_env, when: dev_env_user is defined, become: yes, become_user: '{{dev_env_user}}'}
    - {role: kiosk_env, when: kiosk_env_user is defined, become: yes, become_user: '{{kiosk_env_user}}'}
