---
- hosts: raspi
  vars_files:
    - vars/vault_wifi_key.yml
    - vars/main.yml
  roles:
    - {role: raspi_common, become: yes}
    - {role: geerlingguy.firewall, become: yes}
    - {role: raspi_network}
