---
- name: Check existence of lightdm.conf
  stat: path='/etc/lightdm/lightdm.conf'
  register: stat_lightdm_conf

- name: Set account for auto login [autologin-user]
  become: yes
  become_user: root
  ini_file:
    dest: /etc/lightdm/lightdm.conf
    section: SeatDefaults
    option: autologin-user
    value: '{{kiosk_env_user}}'
    no_extra_spaces: yes
  when: '{{stat_lightdm_conf.stat.exists}} and {{kiosk_env_autologin_enabled}}'
  tags:
    - autologin
    - need_root

- name: Set account for auto login [autologin-user-timeout]
  become: yes
  become_user: root
  ini_file:
    dest: /etc/lightdm/lightdm.conf
    section: SeatDefaults
    option: autologin-user-timeout
    value: 0
    no_extra_spaces: yes
  when: '{{stat_lightdm_conf.stat.exists}} and {{kiosk_env_autologin_enabled}}'
  tags:
    - autologin
    - need_root

- name: Modify startup script for auto login
  become: yes
  become_user: root
  ini_file:
    dest: /etc/systemd/system/autologin@.service
    section: Service
    option: ExecStart
    value: '-/sbin/agetty --autologin {{kiosk_env_user}} --noclear %I $TERM'
    no_extra_spaces: yes
  when: '{{kiosk_env_autologin_enabled}}'
  tags:
    - autologin
    - need_root

- name: Disable cursor
  become: yes
  become_user: root
  ini_file:
    dest: /etc/lightdm/lightdm.conf
    section: SeatDefaults
    option: xserver-command
    value: 'X -nocursor'
    no_extra_spaces: yes
  when: '{{stat_lightdm_conf.stat.exists}} and {{not kiosk_env_cursor_enabled}}'
  tags:
    - cursor
    - need_root

- name: Enable cursor
  become: yes
  become_user: root
  ini_file:
    dest: /etc/lightdm/lightdm.conf
    section: SeatDefaults
    option: xserver-command
    value: 'X'
    no_extra_spaces: yes
  when: '{{stat_lightdm_conf.stat.exists}} and {{kiosk_env_cursor_enabled}}'
  tags:
    - cursor
    - need_root

- name: Check existence of config file for LXDE panel
  stat: path='~/.config/lxpanel/LXDE-pi/panels/panel'
  register: stat_LXDE_panel
  tags:
    - lxde_panel

- name: Make LXDE panel hide automatically | enable autohide
  lineinfile:
    dest: '~/.config/lxpanel/LXDE-pi/panels/panel'
    regexp: 'autohide[ ]*='
    line: 'autohide=1'
  when: '{{stat_LXDE_panel.stat.exists}} and {{kiosk_env_autohide_enabled}}'
  tags:
    - lxde_panel

- name: Disable autohide of LXDE panel
  lineinfile:
    dest: '~/.config/lxpanel/LXDE-pi/panels/panel'
    regexp: 'autohide[ ]*='
    line: 'autohide=0'
  when: '{{stat_LXDE_panel.stat.exists}} and not {{kiosk_env_autohide_enabled}}'
  tags:
    - lxde_panel
  
- name: Make LXDE panel hide automatically | set panel height
  lineinfile:
    dest: '~/.config/lxpanel/LXDE-pi/panels/panel'
    regexp: 'heightwhenhidden[ ]*='
    line: 'heightwhenhidden={{kiosk_env_autohide_panel_height}}'
  when: '{{stat_LXDE_panel.stat.exists}} and {{kiosk_env_autohide_enabled}}'
  tags:
    - lxde_panel

- name: Install xscreensaver
  become: yes
  become_user: root
  apt:
    name: xscreensaver
    state: latest
    update_cache: yes
  tags:
    - screensaver
    - apt
    - need_root

- name: "Create .xinitrc if it doesn't exist"
  copy:
    force: no
    dest: '~/.xinitrc'
    src: '.xinitrc'
    mode: 0644
  tags:
    - always

- name: Add xscreensaver setting [~/.xinitrc]
  lineinfile:
    dest: '~/.xinitrc'
    line: 'xscreensaver -no-splash &'
    insertbefore: BOF
  tags:
    - screensaver

- name: Add xscreensaver setting [~/.Xresources]
  blockinfile:
    dest: '~/.Xresources'
    create: yes
    insertafter: EOF
    block: |
      xscreensaver.timeout: {{kiosk_env_xscreensaver.timeout}}
      xscreensaver.mode: {{kiosk_env_xscreensaver.mode}}
      xscreensaver.dpmsEnabled: {{kiosk_env_xscreensaver.dpmsEnabled}}
      xscreensaver.dpmsQuickoffEnabled: {{kiosk_env_xscreensaver.dpmsQuickoffEnabled}}
      xscreensaver.dpmsStandby: {{kiosk_env_xscreensaver.dpmsStandby}}
      xscreensaver.dpmsSuspend: {{kiosk_env_xscreensaver.dpmsSuspend}}
      xscreensaver.dpmsOff: {{kiosk_env_xscreensaver.dpmsOff}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK xscreensaver"
  tags:
    - cron

- name: Enable mail from crontab
  cron:
    env: yes
    name: MAILTO
    state: absent
    user: '{{kiosk_env_user}}'
  when: '{{kiosk_env_cron_mail_enabled}}'
  tags:
    - screensaver
    - cron

- name: Disable mail from crontab
  cron:
    env: yes
    name: MAILTO
    value: ''
    user: '{{kiosk_env_user}}'
  when: '{{not kiosk_env_cron_mail_enabled}}'
  tags:
    - screensaver
    - cron

- name: Add crontab entries for xscreensaver | activate screensaver
  cron:
    name: 'Activate xscreensaver'
    user: '{{kiosk_env_user}}'
    minute: '{{kiosk_env_xscreensaver_activate_time.minute}}'
    hour: '{{kiosk_env_xscreensaver_activate_time.hour}}'
    job: 'DISPLAY=:0 /usr/bin/xscreensaver-command -activate'
  when: '{{kiosk_env_xscreensaver_cron_enabled}}'
  tags:
    - screensaver
    - cron

- name: Add crontab entries for xscreensaver | deactivate screensaver
  cron:
    name: 'Deactivate xscreensaver'
    user: '{{kiosk_env_user}}'
    minute: '{{kiosk_env_xscreensaver_deactivate_time.minute}}'
    hour: '{{kiosk_env_xscreensaver_deactivate_time.hour}}'
    job: 'DISPLAY=:0 /usr/bin/xscreensaver-command -deactivate'
  when: '{{kiosk_env_xscreensaver_cron_enabled}}'
  tags:
    - screensaver
    - cron

- name: Remove crontab entries for xscreensaver | activate screensaver
  cron:
    name: 'Activate xscreensaver'
    user: '{{kiosk_env_user}}'
    state: absent
  when: '{{not kiosk_env_xscreensaver_cron_enabled}}'
  tags:
    - screensaver
    - cron

- name: Remove crontab entries for xscreensaver | deactivate screensaver
  cron:
    name: 'Deactivate xscreensaver'
    user: '{{kiosk_env_user}}'
    state: absent
  when: '{{not kiosk_env_xscreensaver_cron_enabled}}'
  tags:
    - screensaver
    - cron

- name: Rotate screen upside down
  become: yes
  become_user: root
  lineinfile:
    dest: /boot/config.txt
    line: 'lcd_rotate=2'
    regexp: '^#? *lcd_rotate'
  tags:
    - screen_rotation
    - need_root

- name: Modify backlight brightness | check if file exists
  stat: path='/sys/class/backlight/rpi_backlight/brightness'
  register: stat_rpi_backlight_brightness
  tags:
    - backlight

# This task fails with 'permision denied' error!
# - name: Modify backlight brightness | modify brightness
#   become: yes
#   become_user: root
#   template:
#     dest: '/sys/class/backlight/rpi_backlight/brightness'
#     src: rpi_backlight_brightness.j2
#     mode: 0644
#   when: stat_rpi_backlight_brightness.stat.exists

- name: Modify backlight brightness | create file
  template:
    dest: '~/brightness'
    src: rpi_backlight_brightness.j2
    mode: 0644
  when: stat_rpi_backlight_brightness.stat.exists
  notify: Change brightness
  tags:
    - backlight
